import { CONFIG as SERVER_CONFIG } from "../../config.js";

/**
 * Bunker-specific view of the process configuration. Values remain defined in
 * the legacy composition config until all deployment environments consume the
 * modular names directly.
 */
export const CONFIG = {
  MIN_PLAYERS: SERVER_CONFIG.MIN_PLAYERS,
  MAX_PLAYERS: SERVER_CONFIG.MAX_PLAYERS,
  TOTAL_ROUNDS: SERVER_CONFIG.TOTAL_ROUNDS,
  ATTRIBUTE_COUNT: SERVER_CONFIG.ATTRIBUTE_COUNT,
  CATASTROPHE_REVEAL_TIME: SERVER_CONFIG.CATASTROPHE_REVEAL_TIME,
  BUNKER_EXPLORE_TIME: SERVER_CONFIG.BUNKER_EXPLORE_TIME,
  DISCUSSION_TIME: SERVER_CONFIG.DISCUSSION_TIME,
  VOTE_TIME: SERVER_CONFIG.VOTE_TIME,
  TIEBREAK_DEFENSE_TIME: SERVER_CONFIG.TIEBREAK_DEFENSE_TIME,
  RESULT_DISPLAY_TIME: SERVER_CONFIG.RESULT_DISPLAY_TIME,
  BOT_ACTION_DELAY_MIN: SERVER_CONFIG.BOT_ACTION_DELAY_MIN,
  BOT_ACTION_DELAY_MAX: SERVER_CONFIG.BOT_ACTION_DELAY_MAX,
} as const;
